name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.region }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name sockshop
          kubectl config set-context --current --namespace=sock-shop

  

      - name: Update helm charts
        run: helm repo update

      - name: Install Helm Charts
        run: |
          helm upgrade --install certificate jetstack/cert-manager
          helm upgrade --install prometheus prometheus/kube-prometheus-stack
          helm upgrade --install ingress ingress/ingress-nginx

      - name: run lucky files
        run: kubectl apply -f lucky/.
