name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.region }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name sockshop
          kubectl config set-context --current --namespace=sock-shop

      - name: Run Lucky files
        run: kubectl apply -f lucky/.

      - name: Update Helm Repositories
        run: helm repo update

      - name: Install Helm Charts
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

          helm install certificate jetstack/cert-manager
          helm install prometheus prometheus/kube-prometheus-stack
          helm install ingress ingress-nginx/ingress-nginx

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
